package project.celine.infinitescroll.model.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import project.celine.infinitescroll.model.RecordEntity;

import project.celine.infinitescroll.model.dao.RecordEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordEntityDaoConfig;

    private final RecordEntityDao recordEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordEntityDaoConfig = daoConfigMap.get(RecordEntityDao.class).clone();
        recordEntityDaoConfig.initIdentityScope(type);

        recordEntityDao = new RecordEntityDao(recordEntityDaoConfig, this);

        registerDao(RecordEntity.class, recordEntityDao);
    }
    
    public void clear() {
        recordEntityDaoConfig.getIdentityScope().clear();
    }

    public RecordEntityDao getRecordEntityDao() {
        return recordEntityDao;
    }

}
