package project.celine.infinitescroll.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "RECORD_ENTITY".
 */
public class RecordEntity {

    private Long id;
    private Long recordId;
    private String note;
    private String currency;
    private String sender;
    private String recipient;
    private Integer amount;
    private java.util.Date created;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RecordEntity() {
    }

    public RecordEntity(Long id) {
        this.id = id;
    }

    public RecordEntity(Long id, Long recordId, String note, String currency, String sender, String recipient, Integer amount, java.util.Date created) {
        this.id = id;
        this.recordId = recordId;
        this.note = note;
        this.currency = currency;
        this.sender = sender;
        this.recipient = recipient;
        this.amount = amount;
        this.created = created;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRecordId() {
        return recordId;
    }

    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getRecipient() {
        return recipient;
    }

    public void setRecipient(String recipient) {
        this.recipient = recipient;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
